### ISSUE TITLE
return types

### ISSUE THREAD

**Issue by JMensch** [OpenDataPhillyAPI/bike_racks#2]
@blindman Do you think we should be reading in the responses (e.g. CSV) and providing extended return types or simply wrapping their existing URLs?

**Comment by blindman** [comment]
I'm not really sure.  Reading from CSV wouldn't be as "real-time" as if we were to wrap the URLs directly and extend those.  The CSV route would give a bit more flexibility as far as creating a graph type structure might go (I'm just taking a guess as to how it's all structured).  You have way more knowledge than myself regarding things like that though.
